//***************************************************************************
//                          pvapp.h  -  description
//                             -------------------
//  begin            : mié feb 19 20:44:33 2014
//  generated by     : pvdevelop (C) Lehrig Software Engineering
//  email            : lehrig@t-online.de
//***************************************************************************
#ifndef _PVAPP_H_
#define _PVAPP_H_
#define PI 3.141592f
#ifdef USE_INETD
static int trace=0; // todo: set trace=0 if you do not want printf() within event loop
#else
static int trace=1; // todo: set trace=0 if you do not want printf() within event loop
#endif
#include <math.h>
#include "processviewserver.h"
// todo: comment me out
#include "rlmodbusclient.h"
//#include "rlsiemenstcpclient.h"
//#include "rlppiclient.h"
#include "rldataacquisition.h"
#include "modbusdaemon.h"             // this is generated
//#include "siemensdaemon.h"            // this is generated
//#include "ppidaemon.h"                // this is generated
enum{
    ADMIN =1,
    SCADA =2,
    GRAFICA=3

};

int show_mask3(PARAM *p);
int show_mask1(PARAM *p);
int show_mask2(PARAM *p);
int show_mask3(PARAM *p);

#endif
